#!/usr/bin/env python3
"""Generates include/fpm/fixed/detail/polynomials.hpp: minimax polynomial coefficients for the approximations in <fpm/fixed/math.hpp>.

Each function is approximated as f(x) = base(x) + x * Q(s(x)), with Q a polynomial of degree n in s, minimizing the
maximum weighted error (Remez exchange algorithm), for each degree. <fpm/fixed/math.hpp> selects the lowest degree with enough
precision for each type at compile time, so only the coefficients that are used end up in a program.

Requires mpmath (pip install mpmath). Takes a few minutes.
Usage: tools/polynomials.py [output path]
"""
import sys
import mpmath as mp

mp.mp.dps = 120

# Each function is approximated as  f(x) = base(x) + x * Q(s(x))  with Q a polynomial of degree n in s,
# minimizing max |w(x) * (approximation - f(x))| (absolute error of the final result in its own scale).

def remez(g, w, a, b, n, iters=60):
    """Minimax polynomial p of degree n on [a, b] minimizing max |w(s) (p(s) - g(s))|."""
    # Initial reference: Chebyshev extrema
    ref = [ (a + b) / 2 - (b - a) / 2 * mp.cos(mp.pi * (i + mp.mpf(0.5)) / (n + 2)) for i in range(n + 2) ]
    E = mp.mpf(0)
    for it in range(iters):
        # Solve p(s_i) + (-1)^i E / w(s_i) = g(s_i)
        A = mp.matrix(n + 2, n + 2); y = mp.matrix(n + 2, 1)
        for i, s in enumerate(ref):
            for k in range(n + 1):
                A[i, k] = s ** k
            A[i, n + 1] = (-1) ** i / w(s)
            y[i] = g(s)
        sol = mp.lu_solve(A, y)
        c = [sol[k] for k in range(n + 1)]; E = sol[n + 1]
        err = lambda s: w(s) * (mp.polyval(c[::-1], s) - g(s))
        # Locate extrema: dense sampling, then refine each alternating lobe
        N = 40 * (n + 2)
        xs = [x for x in ((a + b) / 2 - (b - a) / 2 * mp.cos(mp.pi * i / N) for i in range(N + 1)) if w(x) != 0]
        es = [err(x) for x in xs]
        # split into sign lobes
        lobes = []; cur = [0]
        for i in range(1, len(xs)):
            if (es[i] >= 0) == (es[cur[0]] >= 0):
                cur.append(i)
            else:
                lobes.append(cur); cur = [i]
        lobes.append(cur)
        ext = []
        for lobe in lobes:
            i = max(lobe, key=lambda j: abs(es[j]))
            lo = xs[max(i - 1, 0)]; hi = xs[min(i + 1, len(xs) - 1)]
            # golden section on |err|
            f = lambda x: -abs(err(x))
            for _ in range(80):
                m1 = lo + (hi - lo) * 0.381966; m2 = lo + (hi - lo) * 0.618034
                if f(m1) < f(m2): hi = m2
                else: lo = m1
            x = (lo + hi) / 2
            if w(x) != 0: ext.append((x, err(x)))
        # keep n+2 alternating extrema with largest magnitudes
        while len(ext) > n + 2:
            # drop the smaller of the two ends or merge same-sign neighbours
            if abs(ext[0][1]) < abs(ext[-1][1]): ext.pop(0)
            else: ext.pop()
        if len(ext) < n + 2:
            break
        new_ref = [x for x, _ in ext]
        maxerr = max(abs(e) for _, e in ext)
        if abs(maxerr - abs(E)) / abs(E) < mp.mpf(10) ** -12:
            ref = new_ref
            break
        ref = new_ref
    maxerr = max(abs(err(x)) for x in [ (a + b) / 2 - (b - a) / 2 * mp.cos(mp.pi * i / 4000) for i in range(4001) ] if w(x) != 0)
    return c, maxerr


ln2 = mp.log(2)
functions = {
    # 2^f = 1 + f Q(f), f in [0, 1]: relative error
    'exp2': (lambda f: (mp.power(2, f) - 1) / f if f != 0 else ln2, lambda f: f / mp.power(2, f), mp.mpf(0), mp.mpf(1)),
    # log2(1 + t) = t Q(t), t in [sqrt(2)/2 - 1, sqrt(2) - 1]: absolute error
    'log2': (lambda t: mp.log(1 + t, 2) / t if t != 0 else 1 / ln2, lambda t: abs(t), mp.sqrt(2) / 2 - 1, mp.sqrt(2) - 1),
    # sin(pi/2 u) = u Q(u^2), u in [0, 1]: absolute error, as a function of s = u^2
    'sin': (lambda s: mp.sin(mp.pi / 2 * mp.sqrt(s)) / mp.sqrt(s) if s != 0 else mp.pi / 2, lambda s: mp.sqrt(s), mp.mpf(0), mp.mpf(1)),
    # atan(x) = x Q(x^2), x in [0, 1]: absolute error, as a function of s = x^2
    'atan': (lambda s: mp.atan(mp.sqrt(s)) / mp.sqrt(s) if s != 0 else mp.mpf(1), lambda s: mp.sqrt(s), mp.mpf(0), mp.mpf(1)),
}

degrees = {'exp2': (2, 11), 'log2': (2, 22), 'sin': (2, 9), 'atan': (2, 22)}
descriptions = {
    'exp2': '(2^f - 1) / f on f in [0, 1] (relative error of 2^f = 1 + f Q(f))',
    'log2': 'log2(1 + t) / t on t in [sqrt(2)/2 - 1, sqrt(2) - 1] (absolute error of log2(1 + t) = t Q(t))',
    'sin': 'sin(pi/2 u) / u in s = u^2 on u in [0, 1] (absolute error of sin(pi/2 u) = u Q(u^2))',
    'atan': 'atan(x) / x in s = x^2 on x in [0, 1] (absolute error of atan(x) = x Q(x^2))',
}

HEADER = """#pragma once

// Minimax polynomial coefficients for the approximations in <fpm/fixed/math.hpp>.
// Generated by tools/polynomials.py: do not edit by hand.

#include <array>
#include <cstddef>
#include <cstdint>

namespace fpm::detail
{
	/// The precision (in bits) of the polynomials of one function, for consecutive degrees
	template<std::size_t N>
	struct polynomial_precision
	{
		int32_t first_degree;
		std::array<int32_t, N> bits;

		/// The lowest degree with at least `target` bits of precision (the highest degree if none has)
		[[nodiscard]] constexpr int32_t degree_for(const int32_t target) const noexcept
		{
			for(std::size_t i = 0; i < N; ++i)
			{
				if(bits[i] >= target)
					return first_degree + static_cast<int32_t>(i);
			}
			return first_degree + static_cast<int32_t>(N) - 1;
		}
	};

"""


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'include/fpm/fixed/detail/polynomials.hpp'
    lines = []
    for name, (lo, hi) in degrees.items():
        g, w, a, b = functions[name]
        lines.append(f'\t/// Minimax polynomials Q for {descriptions[name]}, by degree. Coefficients in Q62, lowest order first.')
        lines.append(f'\ttemplate<int32_t Degree> inline constexpr std::array<int64_t, Degree + 1> {name}_polynomial{{}};')
        bits = []
        for n in range(lo, hi + 1):
            c, e = remez(g, w, a, b, n)
            q62 = [int(mp.nint(x * mp.power(2, 62))) for x in c]
            assert all(abs(x) < 2**63 for x in q62)
            lines.append(f'\ttemplate<> inline constexpr std::array<int64_t, {n + 1}> {name}_polynomial<{n}>{{{", ".join(map(str, q62))}}};')
            bits.append(int(mp.floor(-mp.log(e, 2))))
            print(f'{name} degree {n}: {float(-mp.log(e, 2)):.2f} bits', file=sys.stderr, flush=True)
        lines.append(f'\t/// Precision in bits of {name}_polynomial<Degree>, for degrees {lo} to {hi}')
        lines.append(f'\tinline constexpr polynomial_precision<{hi - lo + 1}> {name}_precision{{{lo}, {{{", ".join(map(str, bits))}}}}};')
        lines.append('')
    with open(path, 'w') as f:
        f.write(HEADER + '\n'.join(lines) + '}\n')


if __name__ == '__main__':
    main()
